baseURL = "http://acad.nuscomputing.com"
languageCode = "en-us"
title = "Academic Liaison - NUS Students' Computing Club"
theme = "gohugo-theme-ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 6
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  mainSections = ["events"]
  favicon = "favicon.ico"
  description = "The website for the Academic Liaison of the NUS Students' Computing Club"
  facebook = "https://www.facebook.com/nuscomputing/"
  twitter = ""
  instagram = ""
  youtube = ""
  github = ""
  linkedin = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-near-black"
  featured_image = "/images/splash_image.jpg"
  recent_posts_number = 2